"""End-to-end 30-minute cron job: fetch live waits, upsert WaitTimeRecord, train ML,
write today's DailyForecast slots.

Daily full-window forecasts (30 days ahead) are generated by train.py.
Runs from GitHub Actions / cron-job.org every 30 min.
"""

import json
import logging
import os
import sys
import uuid
from collections import defaultdict
from datetime import datetime, date, timedelta, timezone
from zoneinfo import ZoneInfo

import httpx
import numpy as np
import psycopg
from pydantic import BaseModel

from model import (
    HEADLINER_RIDE_IDS,
    predict_for_ride,
    train_ride_models,
    _compute_crowd_score,
)
from schemas import DateContext, LagFeatures, RideForecast, RideHistory

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)


class _QueueTimesRide(BaseModel):
    id: int
    name: str
    is_open: bool
    wait_time: int
    last_updated: str


class _QueueTimesLand(BaseModel):
    id: int
    name: str
    rides: list[_QueueTimesRide]


class _QueueTimesResponse(BaseModel):
    lands: list[_QueueTimesLand] = []
    rides: list[_QueueTimesRide] = []


WINDOW_MINUTES = 30
RAW_RETENTION_DAYS = 30
FORECAST_SLOTS_PER_DAY = 48  # 48 × 30 min = 24 h

PARK_TZ = ZoneInfo("America/Los_Angeles")

# Midnight–7:59 AM Pacific has little useful training signal.
PARK_CLOSED_LOCAL_HOURS = frozenset(range(0, 8))

_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "../src/lib/ride-config.json")


def _load_park_configs() -> list[dict]:
    with open(_CONFIG_PATH) as f:
        return json.load(f)["parks"]


def round_to_window(dt: datetime) -> datetime:
    epoch_ms = int(dt.timestamp() * 1000)
    window_ms = WINDOW_MINUTES * 60 * 1000
    rounded = round(epoch_ms / window_ms) * window_ms
    return datetime.fromtimestamp(rounded / 1000, tz=timezone.utc)


def park_date_key(dt: datetime) -> str:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(PARK_TZ).strftime("%Y-%m-%d")


def park_hour(dt: datetime) -> int:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.astimezone(PARK_TZ).hour


def build_forecast_slots(now: datetime, days: int = 1) -> list[datetime]:
    """Build future 30-minute slots for `days` Pacific calendar days starting today."""
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)
    park_midnight = now.astimezone(PARK_TZ).replace(hour=0, minute=0, second=0, microsecond=0)
    slots: list[datetime] = []
    for day_offset in range(days):
        local_day = park_midnight + timedelta(days=day_offset)
        for i in range(FORECAST_SLOTS_PER_DAY):
            local_slot = local_day + timedelta(minutes=i * WINDOW_MINUTES)
            if local_slot.hour in PARK_CLOSED_LOCAL_HOURS:
                continue
            slot = local_slot.astimezone(timezone.utc)
            if slot >= now:
                slots.append(slot)
    return slots


def fetch_live_rides() -> list[dict]:
    park_configs = _load_park_configs()
    rides = []
    for park in park_configs:
        excluded = set(park["excludedRideIds"])
        res = httpx.get(park["queueTimesUrl"], timeout=20.0)
        res.raise_for_status()
        parsed = _QueueTimesResponse.model_validate(res.json())
        for land in parsed.lands:
            for ride in land.rides:
                if ride.id in excluded:
                    continue
                rides.append({
                    "id": ride.id,
                    "name": ride.name,
                    "land_name": land.name,
                    "is_open": ride.is_open,
                    "wait_time": ride.wait_time,
                })
        for ride in parsed.rides:
            if ride.id in excluded:
                continue
            rides.append({
                "id": ride.id,
                "name": ride.name,
                "land_name": "Other",
                "is_open": ride.is_open,
                "wait_time": ride.wait_time,
            })
    return rides


def upsert_wait_records(conn, rides: list[dict], windowed_at: datetime, now: datetime) -> int:
    sql = """
        INSERT INTO "WaitTimeRecord"
            (id, "rideId", "rideName", "landName", "waitTime", "isOpen", "windowedAt", "recordedAt")
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT ("rideId", "windowedAt") DO UPDATE SET
            "waitTime" = EXCLUDED."waitTime",
            "isOpen" = EXCLUDED."isOpen",
            "recordedAt" = EXCLUDED."recordedAt"
    """
    rows = [
        (
            str(uuid.uuid4()),
            r["id"], r["name"], r["land_name"],
            r["wait_time"], r["is_open"], windowed_at, now,
        )
        for r in rides
    ]
    with conn.cursor() as cur:
        cur.executemany(sql, rows)
    return len(rows)


def fetch_history(conn, since: datetime) -> list[RideHistory]:
    sql = """
        SELECT "rideId", "rideName", "landName", "waitTime", "isOpen", "recordedAt"
        FROM "WaitTimeRecord"
        WHERE "recordedAt" >= %s
    """
    with conn.cursor() as cur:
        cur.execute(sql, (since,))
        rows = cur.fetchall()
        result = []
        for row in rows:
            recorded_at = row[5]
            if recorded_at.tzinfo is None:
                recorded_at = recorded_at.replace(tzinfo=timezone.utc)
            result.append(RideHistory(
                ride_id=row[0], ride_name=row[1], land_name=row[2],
                wait_time=row[3], is_open=row[4], recorded_at=recorded_at,
            ))
        return result


def fetch_hourly_archive(conn) -> list[RideHistory]:
    """Pull all HourlyWaitSummary rows for ML training.

    Each row represents one Pacific-local hour; recorded_at is rebuilt as UTC
    for model feature extraction.
    """
    sql = """
        SELECT "rideId", "rideName", "landName", "avgWait", "isOpen", date, hour
        FROM "HourlyWaitSummary"
        WHERE date >= NOW() - INTERVAL '3 years'
    """
    with conn.cursor() as cur:
        cur.execute(sql)
        rows = []
        for row in cur.fetchall():
            local_dt = row[5].replace(
                hour=row[6], minute=0, second=0, microsecond=0, tzinfo=PARK_TZ,
            )
            rows.append(
                RideHistory(
                    ride_id=row[0], ride_name=row[1], land_name=row[2],
                    wait_time=round(row[3]), is_open=row[4],
                    recorded_at=local_dt.astimezone(timezone.utc),
                )
            )
        return rows


def compute_lag_features(history: list[RideHistory]) -> list[RideHistory]:
    """Enrich training records with lag and rolling statistics via dict lookups.

    Uses Python dict lookups rather than SQL LAG() to correctly handle gaps
    (closed days, missing data) without producing wrong values.
    """
    # (ride_id, date_str_pacific, hour) -> avg_wait
    lookup: dict[tuple[int, str, int], float] = {}
    for r in history:
        pdt = r.recorded_at.astimezone(PARK_TZ)
        key = (r.ride_id, pdt.strftime("%Y-%m-%d"), pdt.hour)
        lookup[key] = r.wait_time

    enriched: list[RideHistory] = []
    for r in history:
        pdt = r.recorded_at.astimezone(PARK_TZ)
        d = pdt.date()
        h = pdt.hour

        lag_7d = lookup.get((r.ride_id, str(d - timedelta(days=7)), h), 0.0)
        lag_14d = lookup.get((r.ride_id, str(d - timedelta(days=14)), h), 0.0)

        # 7-day rolling mean/std: average over same hour for prior 7 calendar days
        week_waits: list[float] = []
        for days_back in range(1, 8):
            w = lookup.get((r.ride_id, str(d - timedelta(days=days_back)), h))
            if w is not None:
                week_waits.append(w)

        rolling_mean = float(np.mean(week_waits)) if week_waits else r.wait_time
        rolling_std = float(np.std(week_waits)) if len(week_waits) > 1 else 0.0

        existing = r.lag_features or LagFeatures()
        new_lag = LagFeatures(
            lag_7d_wait=lag_7d,
            lag_14d_wait=lag_14d,
            rolling_7d_mean=rolling_mean,
            rolling_7d_std=rolling_std,
            pct_rides_open=existing.pct_rides_open,
            is_headliner_open=existing.is_headliner_open,
        )
        enriched.append(r.model_copy(update={"lag_features": new_lag}))

    return enriched


def attach_cross_ride_features(
    history: list[RideHistory],
    headliner_ids: frozenset,
) -> list[RideHistory]:
    """Compute pct_rides_open and is_headliner_open from concurrent records."""
    # Group by park-local hour slot
    slot_stats: dict = defaultdict(lambda: {"open": 0, "total": 0, "headliner_open": False})
    for r in history:
        slot = r.recorded_at.astimezone(PARK_TZ).replace(minute=0, second=0, microsecond=0)
        slot_stats[slot]["total"] += 1
        if r.is_open:
            slot_stats[slot]["open"] += 1
        if r.ride_id in headliner_ids and r.is_open:
            slot_stats[slot]["headliner_open"] = True

    enriched: list[RideHistory] = []
    for r in history:
        slot = r.recorded_at.astimezone(PARK_TZ).replace(minute=0, second=0, microsecond=0)
        stats = slot_stats[slot]
        total = stats["total"]
        pct_open = stats["open"] / total if total > 0 else 1.0
        headliner_open = 1.0 if stats["headliner_open"] else 0.0

        existing = r.lag_features or LagFeatures()
        new_lag = existing.model_copy(update={
            "pct_rides_open": pct_open,
            "is_headliner_open": headliner_open,
        })
        enriched.append(r.model_copy(update={"lag_features": new_lag}))

    return enriched


def fetch_date_contexts(conn, dates: list[datetime]) -> dict[str, DateContext]:
    unique_strs = list({park_date_key(d) for d in dates})
    if not unique_strs:
        return {}
    sql = """
        SELECT date::date, tier, "specialEvent", "isHoliday", "isSchoolBreak",
               "tempHigh", "tempLow", "precipMm", "isRainy"
        FROM "DateContext"
        WHERE date::date = ANY(%s)
    """
    result: dict[str, DateContext] = {}
    with conn.cursor() as cur:
        cur.execute(sql, (unique_strs,))
        for row in cur.fetchall():
            key = row[0].strftime("%Y-%m-%d")
            result[key] = DateContext(
                tier=row[1] or 0,
                has_special_event=bool(row[2]),
                is_holiday=bool(row[3]),
                is_school_break=bool(row[4]),
                temp_high=float(row[5]) if row[5] is not None else None,
                temp_low=float(row[6]) if row[6] is not None else None,
                precip_mm=float(row[7]) if row[7] is not None else 0.0,
                is_rainy=bool(row[8]) if row[8] is not None else False,
            )
    return result


def build_prediction_lag_features(
    conn,
    ride_ids: list[int],
    slots: list[datetime],
) -> dict[tuple[int, str, int], LagFeatures]:
    """Fetch historical lag features from HourlyWaitSummary for future prediction slots.

    For each (ride_id, slot), looks up the 7-day and 14-day prior waits and
    computes a rolling 7-day mean/std. pct_rides_open and is_headliner_open
    default to 1.0 (assume all rides open for future predictions).
    """
    if not ride_ids or not slots:
        return {}

    park_slots = [s.astimezone(PARK_TZ) for s in slots]

    # Collect all dates needed for lag lookups (up to 14 days before earliest slot)
    dates_needed: set[str] = set()
    for ps in park_slots:
        d = ps.date()
        for days_back in range(1, 15):
            dates_needed.add(str(d - timedelta(days=days_back)))

    sql = """
        SELECT "rideId", date::date, hour, "avgWait"
        FROM "HourlyWaitSummary"
        WHERE date::date = ANY(%s)
          AND "rideId" = ANY(%s)
    """
    lookup: dict[tuple[int, str, int], float] = {}
    with conn.cursor() as cur:
        cur.execute(sql, (list(dates_needed), ride_ids))
        for row in cur.fetchall():
            ride_id, d, hour, avg_wait = row
            lookup[(ride_id, str(d), hour)] = float(avg_wait)

    result: dict[tuple[int, str, int], LagFeatures] = {}
    for ps in park_slots:
        date_str = ps.strftime("%Y-%m-%d")
        d = ps.date()
        h = ps.hour
        for ride_id in ride_ids:
            lag_7d = lookup.get((ride_id, str(d - timedelta(days=7)), h), 0.0)
            lag_14d = lookup.get((ride_id, str(d - timedelta(days=14)), h), 0.0)
            week_waits = [
                lookup[(ride_id, str(d - timedelta(days=db)), h)]
                for db in range(1, 8)
                if (ride_id, str(d - timedelta(days=db)), h) in lookup
            ]
            rolling_mean = float(np.mean(week_waits)) if week_waits else 0.0
            rolling_std = float(np.std(week_waits)) if len(week_waits) > 1 else 0.0
            # When HEADLINER_RIDE_IDS is empty, training always sees is_headliner_open=0.0
            # (attach_cross_ride_features never sets it True without IDs configured).
            # Prediction must match — using 1.0 here would feed a value the model never saw.
            result[(ride_id, date_str, h)] = LagFeatures(
                lag_7d_wait=lag_7d,
                lag_14d_wait=lag_14d,
                rolling_7d_mean=rolling_mean,
                rolling_7d_std=rolling_std,
                pct_rides_open=1.0,
                is_headliner_open=1.0 if HEADLINER_RIDE_IDS else 0.0,
            )

    return result


def upsert_forecasts(
    conn,
    forecasts_per_slot: list[tuple[datetime, list, int]],
    ride_meta: dict[int, dict],
) -> int:
    """Upsert DailyForecast rows — ON CONFLICT updates existing rows in place."""
    sql = """
        INSERT INTO "DailyForecast"
            (id, "rideId", "rideName", "landName", "forecastFor",
             "predictedWait", "crowdScore", "mlConfidence", "createdAt")
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s)
        ON CONFLICT ("rideId", "forecastFor") DO UPDATE SET
            "predictedWait" = EXCLUDED."predictedWait",
            "crowdScore"    = EXCLUDED."crowdScore",
            "mlConfidence"  = EXCLUDED."mlConfidence",
            "createdAt"     = EXCLUDED."createdAt"
    """
    now = datetime.now(timezone.utc)
    rows = []
    for slot, ride_forecasts, crowd_score in forecasts_per_slot:
        for f in ride_forecasts:
            meta = ride_meta.get(f.ride_id)
            if not meta:
                continue
            rows.append((
                str(uuid.uuid4()),
                f.ride_id, meta["name"], meta["land_name"],
                slot, f.predicted_wait, crowd_score, f.confidence, now,
            ))
    if not rows:
        return 0
    with conn.cursor() as cur:
        cur.executemany(sql, rows)
    return len(rows)


# Keep old name as alias so existing callers (tests) don't break
def insert_forecasts(
    conn,
    forecasts_per_slot: list[tuple[datetime, list, int]],
    ride_meta: dict[int, dict],
) -> int:
    return upsert_forecasts(conn, forecasts_per_slot, ride_meta)


def log_collect_run(
    conn, rows_upserted: int, success: bool, error_message: str | None = None
) -> None:
    sql = """
        INSERT INTO "CollectRun" (id, "ranAt", "rowsUpserted", success, "errorMessage")
        VALUES (%s, %s, %s, %s, %s)
    """
    with conn.cursor() as cur:
        cur.execute(
            sql,
            (str(uuid.uuid4()), datetime.now(timezone.utc), rows_upserted, success, error_message),
        )


def main() -> int:
    db_url = os.environ.get("DATABASE_URL") or os.environ.get("DIRECT_URL")
    if not db_url:
        print("ERROR: DATABASE_URL or DIRECT_URL must be set", file=sys.stderr)
        return 1

    db_url = db_url.replace("?pgbouncer=true", "").replace("&pgbouncer=true", "")

    now = datetime.now(timezone.utc)
    windowed_at = round_to_window(now)
    rows_upserted = 0

    try:
        rides = fetch_live_rides()
        logger.info("Fetched %d rides from queue-times.com", len(rides))

        with psycopg.connect(db_url, autocommit=False) as conn:
            try:
                rows_upserted = upsert_wait_records(conn, rides, windowed_at, now)
                conn.commit()
                logger.info("Upserted %d WaitTimeRecord rows", rows_upserted)

                ride_meta = {r["id"]: {"name": r["name"], "land_name": r["land_name"]} for r in rides}

                # Load training data: 30-day raw + full hourly archive
                raw_history = fetch_history(conn, now - timedelta(days=RAW_RETENTION_DAYS))
                archived_history = fetch_hourly_archive(conn)
                history = raw_history + archived_history
                logger.info(
                    "Loaded %d raw + %d archived = %d total records",
                    len(raw_history), len(archived_history), len(history),
                )

                # Attach DateContext (tier, weather, holiday) to training records
                training_contexts = fetch_date_contexts(conn, [r.recorded_at for r in history])
                history = [
                    r.model_copy(update={"context": training_contexts.get(park_date_key(r.recorded_at), DateContext())})
                    for r in history
                ]

                # Enrich with lag and cross-ride features
                history = compute_lag_features(history)
                history = attach_cross_ride_features(history, HEADLINER_RIDE_IDS)

                trained_models = train_ride_models(history)
                logger.info("Trained %d ride models", len(trained_models))

                # 30-min collect only predicts TODAY's remaining slots (not full 30 days).
                # train.py (daily job) generates the full 30-day window.
                slots = build_forecast_slots(now, days=1)
                date_contexts = fetch_date_contexts(conn, slots)

                # Fetch lag features for prediction slots from HourlyWaitSummary
                lag_map = build_prediction_lag_features(conn, list(trained_models.keys()), slots)

                # Batch-predict per ride (one XGBoost call per ride for all slots)
                all_ride_forecasts: dict[tuple[int, datetime], RideForecast] = {}
                for ride_id, tm in trained_models.items():
                    contexts_list = [date_contexts.get(park_date_key(s)) for s in slots]
                    lags_list = [
                        lag_map.get((ride_id, park_date_key(s), park_hour(s)), LagFeatures())
                        for s in slots
                    ]
                    for slot, f in zip(slots, predict_for_ride(tm, ride_id, slots, contexts_list, lags_list)):
                        all_ride_forecasts[(ride_id, slot)] = f

                # Regroup by slot to compute crowd score
                forecasts_per_slot = []
                for slot in slots:
                    ctx = date_contexts.get(park_date_key(slot))
                    slot_forecasts = [
                        all_ride_forecasts[(rid, slot)]
                        for rid in trained_models
                        if (rid, slot) in all_ride_forecasts
                    ]
                    crowd_score = _compute_crowd_score(slot_forecasts, ctx)
                    forecasts_per_slot.append((slot, slot_forecasts, crowd_score))

                forecast_count = upsert_forecasts(conn, forecasts_per_slot, ride_meta)
                conn.commit()
                logger.info(
                    "Upserted %d DailyForecast rows across %d slots",
                    forecast_count, len(forecasts_per_slot),
                )

                log_collect_run(conn, rows_upserted, success=True)
                conn.commit()
            except Exception:
                conn.rollback()
                raise

        logger.info("Collect run successful")
        return 0
    except Exception as exc:
        logger.error("Collect failed: %s", exc)
        try:
            with psycopg.connect(db_url, autocommit=True) as conn:
                log_collect_run(conn, rows_upserted, success=False, error_message=str(exc))
        except Exception as log_exc:
            logger.error("Failed to log error: %s", log_exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
